---
- name: Update package cache
  package:
    update_cache: yes

- name: Install essential packages
  package:
    name:
      - curl
      - wget
      - git
      - python3
      - python3-pip
      - python3-venv
      - nginx
    state: present

- name: Create webapp user
  user:
    name: "{{ app_user }}"
    system: yes
    shell: /bin/bash
    home: "{{ app_dir }}"
    create_home: yes

- name: Configure firewall (Ubuntu)
  ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ firewall_ports }}"
  when: ansible_os_family == "Debian"

- name: Enable firewall (Ubuntu)
  ufw:
    state: enabled
  when: ansible_os_family == "Debian"

- name: Configure firewall (RHEL)
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  loop: "{{ firewall_ports }}"
  when: ansible_os_family == "RedHat"