---
# tasks/main.yml for role: nginx

- name: Update apt cache before installing Nginx
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: true

- name: Deploy a simple index.html
  copy:
    dest: /var/www/html/index.html
    content: |
      <html>
        <head><title>{{ inventory_hostname }}</title></head>
        <body>
          <h1>This is {{ inventory_hostname }}</h1>
        </body>
      </html>
    owner: www-data
    group: www-data
    mode: "0644"
