# roles/splunk_forwarder/tasks/main.yml
---
- name: Ensure splunk user and group exist
  ansible.builtin.user:
    name: splunk
    shell: /sbin/nologin
    system: true

- name: Download Splunk Universal Forwarder Package
  ansible.builtin.get_url:
    url: "{{ splunk_forwarder_download_url }}"
    dest: "/tmp/splunkforwarder-{{ splunk_forwarder_version }}.{{ 'rpm' if ansible_os_family == 'RedHat' else 'deb' }}"
    mode: "0644"

- name: Install Splunk Forwarder (RedHat/CentOS/RHEL 8+)
  ansible.builtin.dnf: # <--- CHANGED FROM YUM TO DNF
    name: "/tmp/splunkforwarder-{{ splunk_forwarder_version }}.rpm"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install Splunk Forwarder (Debian/Ubuntu)
  ansible.builtin.apt:
    deb: "/tmp/splunkforwarder-{{ splunk_forwarder_version }}.deb"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Enable Splunk boot-start (creates systemd unit)
  ansible.builtin.command:
    cmd: >-
      {{ splunk_forwarder_install_dir }}/bin/splunk enable boot-start
      --accept-license --answer-true -user splunk
    args:
      creates: /etc/systemd/system/splunkforwarder.service

- name: Start Splunk forwarder (ignore failure on first run)
  ansible.builtin.systemd:
    name: splunkforwarder
    state: started
  ignore_errors: true

- name: Configure Splunk Admin credentials
  ansible.builtin.command:
    cmd: >-
      {{ splunk_forwarder_install_dir }}/bin/splunk edit user {{ splunk_forwarder_admin_user }}
      -password '{{ splunk_forwarder_admin_password }}'
      -role admin
      -auth admin:changeme
  register: pwd_change
  changed_when: "'changed' in pwd_change.stdout"

- name: Configure Splunk to forward to central indexer
  ansible.builtin.command:
    cmd: >-
      {{ splunk_forwarder_install_dir }}/bin/splunk add forward-server
      {{ splunk_forwarder_splunk_server }}:{{ splunk_forwarder_splunk_server_port }}
      -auth {{ splunk_forwarder_admin_user }}:{{ splunk_forwarder_admin_password }}
  register: forward_server
  changed_when: "'already exists' not in forward_server.stdout"
  notify: Restart Splunk

- name: Configure forwarder outputs
  ansible.builtin.template:
    src: outputs.conf.j2
    dest: "{{ splunk_forwarder_install_dir }}/etc/system/local/outputs.conf"
  notify: Restart Splunk

- name: Configure forwarder inputs
  ansible.builtin.template:
    src: inputs.conf.j2
    dest: "{{ splunk_forwarder_install_dir }}/etc/system/local/inputs.conf"
  notify: Restart Splunk

- name: Restart Splunk forwarder if forward-server changed
  ansible.builtin.systemd:
    name: splunkforwarder
    state: restarted
  when: forward_server is changed
