---
- name: Install PostgreSQL (Debian/Ubuntu)
  package:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL (RHEL/CentOS)
  package:
    name:
      - postgresql-server
      - postgresql-contrib
      - python3-psycopg2
    state: present
  when: ansible_os_family == "RedHat"

- name: Check if PostgreSQL database is initialized
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version
  when: ansible_os_family == "RedHat"

- name: Initialize PostgreSQL database (RHEL/CentOS)
  command: "{{ postgresql_bin_path }}/postgresql-setup initdb"
  when: ansible_os_family == "RedHat" and not pgdata_dir_version.stat.exists
  become: yes

- name: Start and enable PostgreSQL
  service:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: yes

# Database setup temporarily disabled - PostgreSQL is installed and running
# Manual setup: sudo -u postgres createdb polls_db
# Manual setup: sudo -u postgres psql -c "CREATE USER polls_user WITH PASSWORD 'changeme123';"
# Manual setup: sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE polls_db TO polls_user;"