- name: Install Java
  ansible.builtin.apt:
    name: "{{ java_package }}"
    state: present
    update_cache: yes

- name: Add Jenkins apt key
  ansible.builtin.apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins repo
  ansible.builtin.apt_repository:
    repo: "{{ jenkins_repo }}"
    state: present
    filename: jenkins

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present

- name: Ensure Jenkins service is enabled and running
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: yes
