- name: "Update all packages (Ubuntu: apt / RHEL: yum/dnf)"
  ansible.builtin.package:
    name: "*"
    state: latest
  when: ansible_facts.os_family in ['Debian', 'RedHat']

- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Ensure SSHD config disables root login & password auth
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
  notify: Restart sshd

- name: Open firewall ports via firewalld (RHEL) or ufw (Ubuntu)
  block:
    - name: RHEL | Ensure firewalld is installed and running
      ansible.builtin.dnf:
        name: firewalld
        state: present
      when: ansible_facts.os_family == "RedHat"

    - name: RHEL | Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
      when: ansible_facts.os_family == "RedHat"

    - name: RHEL | Add allowed ports to firewalld
      ansible.builtin.command:
        cmd: "firewall-cmd --permanent --add-port={{ item.port }}/{{ item.proto }}"
      loop: "{{ firewall_allowed_ports }}"
      when: ansible_facts.os_family == "RedHat" and item.rule == "enabled"
      register: firewall_changes
      changed_when: "'ALREADY_ENABLED' not in firewall_changes.stderr"

    - name: RHEL | Reload firewalld
      ansible.builtin.command:
        cmd: "firewall-cmd --reload"
      when: ansible_facts.os_family == "RedHat" and firewall_changes is changed

    - name: Ubuntu | Ensure ufw is installed
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true
      when: ansible_facts.os_family == "Debian"

    - name: Ubuntu | Allow ports in ufw
      ansible.builtin.command:
        cmd: "ufw allow {{ item.port }}/{{ item.proto }}"
      loop: "{{ firewall_allowed_ports }}"
      when: ansible_facts.os_family == "Debian" and item.rule == "enabled"
      register: ufw_changes
      changed_when: "'Rule added' in ufw_changes.stdout or 'Rule updated' in ufw_changes.stdout"

    - name: Ubuntu | Enable ufw
      ansible.builtin.command:
        cmd: ufw --force enable
      when: ansible_facts.os_family == "Debian"
