---
# roles/splunk_forwarder/defaults/main.yml
# Sensible default values for Splunk Universal Forwarder deployment

splunk_forwarder_version: "9.4.0"

# Use local file instead of download URL
# Place the Splunk Universal Forwarder packages in files/downloads/ directory
splunk_forwarder_use_local_file: true
splunk_forwarder_local_file_rpm: "splunkforwarder-{{ splunk_forwarder_version }}-Linux-x86_64.rpm"
splunk_forwarder_local_file_deb: "splunkforwarder-{{ splunk_forwarder_version }}-linux-2.6-amd64.deb"
# Fallback download URL (if local file not available)
splunk_forwarder_download_url: ""

splunk_forwarder_install_dir: "/opt/splunkforwarder"

splunk_forwarder_admin_user: "admin"
# IMPORTANT: This should be encrypted with Ansible Vault in a real environment!
# For a quick start, you can set it here, but it's not secure.
splunk_forwarder_admin_password: "lulu618" # <<< CHANGE THIS AND VAULT IT!

# Central Splunk Indexer/Search Head address and receiving port
# This is where all forwarders will send their data.
splunk_forwarder_splunk_server: "splunk.simo.local" # Or your Splunk server's IP, e.g., "192.168.198.134"
splunk_forwarder_splunk_server_port: 9997

# Default inputs to monitor. These can be overridden in group_vars if needed.
splunk_forwarder_inputs:
  - stanza: "[monitor:///var/log/messages]"
    index: "os"
    sourcetype: "linux_syslog"
  - stanza: "[monitor:///var/log/secure]"
    index: "os"
    sourcetype: "linux_secure"
  - stanza: "[monitor:///var/log/audit/audit.log]"
    index: "os"
    sourcetype: "linux_audit"
