---
# roles/splunk_indexer/handlers/main.yml
# Handlers for Splunk Indexer service management

- name: Restart Splunk
  ansible.builtin.systemd:
    name: splunk
    state: restarted
  listen: "restart splunk"

- name: Reload Splunk
  ansible.builtin.systemd:
    name: splunk
    state: reloaded
  listen: "reload splunk"

- name: Stop Splunk
  ansible.builtin.systemd:
    name: splunk
    state: stopped
  listen: "stop splunk"

- name: Start Splunk
  ansible.builtin.systemd:
    name: splunk
    state: started
  listen: "start splunk"
