---
# tasks/main.yml for role: fail2ban

- name: Update apt cache before installing fail2ban
  apt:
    update_cache: yes

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Deploy custom jail.local for SSH and Nginx
  copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled  = true
      port     = ssh
      filter   = sshd
      logpath  = /var/log/auth.log
      maxretry = 5
      bantime  = 600

      [nginx-http-auth]
      enabled  = true
      filter   = nginx-http-auth
      port     = http,https
      logpath  = /var/log/nginx/error.log
      maxretry = 3
      bantime  = 600
    owner: root
    group: root
    mode: "0644"

- name: Ensure fail2ban is started and enabled
  service:
    name: fail2ban
    state: started
    enabled: true
