---
# roles/splunkforwarder/tasks/main.yml

- name: Ensure apt cache is updated
  apt:
    update_cache: yes

- name: Download latest Splunk UF .deb package
  get_url:
    url: "https://download.splunk.com/products/universalforwarder/releases/9.2.1/linux/splunkforwarder-9.2.1-77f73c9edb85-linux-2.6-amd64.deb"
    dest: /tmp/splunkforwarder.deb
    mode: "0644"

- name: Install Splunk UF .deb package
  apt:
    deb: /tmp/splunkforwarder.deb

- name: Create splunk user (if not already created by installer)
  user:
    name: splunk
    system: yes
    shell: /bin/false
  ignore_errors: yes

- name: Accept license and start Splunk UF once
  become: true
  become_user: splunk
  shell: |
    /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt
  args:
    creates: /opt/splunkforwarder/etc/.ui_login

- name: Configure outputs.conf
  template:
    src: outputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    owner: splunk
    group: splunk
    mode: "0644"

- name: Restart Splunk UF to apply config
  become: true
  become_user: splunk
  shell: /opt/splunkforwarder/bin/splunk restart

- name: Enable Splunk UF to start on boot
  become: true
  shell: /opt/splunkforwarder/bin/splunk enable boot-start -user splunk
  args:
    creates: /etc/systemd/system/SplunkForwarder.service
