---
# tasks/main.yml for role: splunkforwarder

- name: Update apt cache before installing dependencies
  apt:
    update_cache: yes

- name: Install required libraries for Splunk UF
  apt:
    name:
      - libpam0g
      - libz1
      - libssl1.1 # adjust if a newer libssl package is needed
    state: present

- name: Download Splunk Universal Forwarder tarball
  get_url:
    url: "{{ splunk_forwarder_url }}"
    dest: /tmp/splunkforwarder.tgz
    mode: "0644"
    force: yes

- name: Extract Splunk Forwarder to /opt
  unarchive:
    src: /tmp/splunkforwarder.tgz
    dest: /opt
    remote_src: yes

- name: Create splunk system user
  user:
    name: splunk
    shell: /bin/false
    system: yes

- name: Change ownership of Splunk folder to splunk user
  file:
    path: /opt/splunkforwarder
    owner: splunk
    group: splunk
    recurse: yes

- name: Accept Splunk license and start Splunk UF (once)
  become: true
  become_user: splunk
  shell: |
    /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt
  args:
    creates: /opt/splunkforwarder/etc/.ui_login

- name: Configure outputs.conf for Splunk UF
  template:
    src: outputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    owner: splunk
    group: splunk
    mode: "0644"

- name: Restart Splunk Universal Forwarder to apply config
  become: true
  become_user: splunk
  shell: /opt/splunkforwarder/bin/splunk restart

- name: Enable Splunk UF to start on boot
  become: true
  become_user: splunk
  shell: |
    /opt/splunkforwarder/bin/splunk enable boot-start -user splunk
  args:
    creates: /etc/systemd/system/SplunkForwarder.service
