---
# tasks/main.yml for role: common

- name: Update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install essential utilities
  apt:
    name:
      - curl
      - wget
      - htop
      - unzip
      - git
    state: present

- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Allow SSH through UFW
  ufw:
    rule: allow
    name: OpenSSH

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
