# roles/prometheus/handlers/main.yml
---
- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
