# playbooks/prometheus.yml
---
- name: Deploy Prometheus Server and Node Exporters
  hosts: ubuntu, rhel_indexers, rhel_forwarders # Apply to all Linux hosts that need monitoring
  become: true
  roles:
    - prometheus
