---
- name: “Apply Linux baseline to all Linux hosts”
  hosts: ubuntu:rhel:adserver
  become: yes
  roles:
    - linux_baseline

- name: “Configure Prometheus on its host”
  hosts: prometheus.lab.local
  become: yes
  roles:
    - prometheus

- name: “Configure Grafana on its host”
  hosts: prometheus.lab.local
  become: yes
  roles:
    - grafana

- name: “Configure Jenkins on its host”
  hosts: jenkins.lab.local
  become: yes
  roles:
    - jenkins

- name: “Configure Splunk Universal Forwarder on RHEL”
  hosts: splunkagent.lab.local
  become: yes
  roles:
    - splunk_forwarder

- name: “Push firewall rules to pfSense”
  hosts: pfsense.lab.local
  gather_facts: no
  roles:
    - firewall_rules
