---
# playbooks/splunk_indexer.yml
# Playbook to deploy Splunk Enterprise Indexer

- name: Deploy Splunk Enterprise Indexer
  hosts: rhel_indexers
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update system packages (RHEL/CentOS)
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
      when: ansible_os_family == 'RedHat'
      tags: ["system_update"]

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - firewalld
          - python3-firewall
          - wget
          - curl
          - tar
          - gzip
        state: present
      when: ansible_os_family == 'RedHat'
      tags: ["dependencies"]

    - name: Ensure firewalld is running
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      when: ansible_os_family == 'RedHat'
      tags: ["firewall"]

  roles:
    - role: linux_baseline
      tags: ["baseline"]
    - role: splunk_indexer
      tags: ["splunk"]

  post_tasks:
    - name: Verify Splunk is running
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}:{{ splunk_indexer_web_port }}/en-US/account/login"
        method: GET
        status_code: 200
      register: splunk_health_check
      retries: 5
      delay: 10
      tags: ["verification"]

    - name: Display deployment summary
      ansible.builtin.debug:
        msg: |
          ========================================
          Splunk Enterprise Indexer Deployment Complete!
          ========================================

          Server: {{ ansible_hostname }} ({{ ansible_default_ipv4.address }})

          Access Information:
          - Web Interface: http://{{ ansible_default_ipv4.address }}:{{ splunk_indexer_web_port }}
          - Username: {{ splunk_indexer_admin_user }}
          - Password: {{ splunk_indexer_admin_password }}

          Network Configuration:
          - Web Port: {{ splunk_indexer_web_port }}
          - Management Port: {{ splunk_indexer_mgmt_port }}
          - Receiving Port: {{ splunk_indexer_receiving_port }}

          Configured Indexes:
          {% for index in splunk_indexer_indexes %}
          - {{ index.name }}
          {% endfor %}

          Next Steps:
          1. Access the web interface and complete initial setup
          2. Configure forwarders to send data to {{ ansible_default_ipv4.address }}:{{ splunk_indexer_receiving_port }}
          3. Set up data inputs and search configurations as needed

          ========================================
      tags: ["summary"]
